const cards = {
    products: [
        {
            _id: '1',
            name: 'T-123',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 120,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 0,
        },
        {
            _id: '2',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-2.png',
            price: 120,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '3',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-3.png',
            price: 120,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '4',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-4.png',
            price: 120,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '5',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-4.png',
            price: 90,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '6',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-4.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '7',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 0,
        },
        {
            _id: '8',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '9',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '10',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 0,
        },
        {
            _id: '11',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '12',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '13',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 0,
        },
        {
            _id: '14',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
    ],
}

export default cards;