const cards = {
    products: [
        {
            _id: '1',
            name: 'T-123',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 120,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 0,
        },
        {
            _id: '2',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 120,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '3',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 120,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '4',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 120,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '5',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 90,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '6',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
        {
            _id: '6',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 0,
        },
        {
            _id: '6',
            name: 'T-Shirt',
            category: 'Shirts',
            image: '/images/p-1.png',
            price: 100,
            brand: 'xz',
            description: 'high quality product',
            countInStock: 10,
        },
    ],
}

export default cards;